/*
 * generated by Xtext 2.19.0
 */
package es.us.isa.interparamdep.ide

import com.google.inject.Guice
import es.us.isa.interparamdep.InterparameterDependenciesLanguageRuntimeModule
import es.us.isa.interparamdep.InterparameterDependenciesLanguageStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class InterparameterDependenciesLanguageIdeSetup extends InterparameterDependenciesLanguageStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new InterparameterDependenciesLanguageRuntimeModule, new InterparameterDependenciesLanguageIdeModule))
	}
	
}
