/*
 * generated by Xtext 2.19.0
 */
package es.us.isa.interparamdep.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractInterparameterDependenciesLanguageValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(es.us.isa.interparamdep.interparameterDependenciesLanguage.InterparameterDependenciesLanguagePackage.eINSTANCE);
		return result;
	}
}
