/**
 * generated by Xtext 2.19.0
 */
package es.us.isa.interparamdep.interparameterDependenciesLanguage;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Positive Clause2</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.PositiveClause2#getFirstElement <em>First Element</em>}</li>
 *   <li>{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.PositiveClause2#getLogicalOp <em>Logical Op</em>}</li>
 *   <li>{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.PositiveClause2#getAdditionalElements <em>Additional Elements</em>}</li>
 * </ul>
 *
 * @see es.us.isa.interparamdep.interparameterDependenciesLanguage.InterparameterDependenciesLanguagePackage#getPositiveClause2()
 * @model
 * @generated
 */
public interface PositiveClause2 extends PositiveFullClause2
{
  /**
   * Returns the value of the '<em><b>First Element</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First Element</em>' containment reference.
   * @see #setFirstElement(PositiveAtomic)
   * @see es.us.isa.interparamdep.interparameterDependenciesLanguage.InterparameterDependenciesLanguagePackage#getPositiveClause2_FirstElement()
   * @model containment="true"
   * @generated
   */
  PositiveAtomic getFirstElement();

  /**
   * Sets the value of the '{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.PositiveClause2#getFirstElement <em>First Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First Element</em>' containment reference.
   * @see #getFirstElement()
   * @generated
   */
  void setFirstElement(PositiveAtomic value);

  /**
   * Returns the value of the '<em><b>Logical Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Logical Op</em>' attribute.
   * @see #setLogicalOp(String)
   * @see es.us.isa.interparamdep.interparameterDependenciesLanguage.InterparameterDependenciesLanguagePackage#getPositiveClause2_LogicalOp()
   * @model
   * @generated
   */
  String getLogicalOp();

  /**
   * Sets the value of the '{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.PositiveClause2#getLogicalOp <em>Logical Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Logical Op</em>' attribute.
   * @see #getLogicalOp()
   * @generated
   */
  void setLogicalOp(String value);

  /**
   * Returns the value of the '<em><b>Additional Elements</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Additional Elements</em>' containment reference.
   * @see #setAdditionalElements(EObject)
   * @see es.us.isa.interparamdep.interparameterDependenciesLanguage.InterparameterDependenciesLanguagePackage#getPositiveClause2_AdditionalElements()
   * @model containment="true"
   * @generated
   */
  EObject getAdditionalElements();

  /**
   * Sets the value of the '{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.PositiveClause2#getAdditionalElements <em>Additional Elements</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Additional Elements</em>' containment reference.
   * @see #getAdditionalElements()
   * @generated
   */
  void setAdditionalElements(EObject value);

} // PositiveClause2
