/**
 * generated by Xtext 2.19.0
 */
package es.us.isa.interparamdep.interparameterDependenciesLanguage.impl;

import es.us.isa.interparamdep.interparameterDependenciesLanguage.ComparisonDependency;
import es.us.isa.interparamdep.interparameterDependenciesLanguage.InterparameterDependenciesLanguagePackage;
import es.us.isa.interparamdep.interparameterDependenciesLanguage.Param;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Comparison Dependency</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.impl.ComparisonDependencyImpl#getParam1 <em>Param1</em>}</li>
 *   <li>{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.impl.ComparisonDependencyImpl#getArithOp <em>Arith Op</em>}</li>
 *   <li>{@link es.us.isa.interparamdep.interparameterDependenciesLanguage.impl.ComparisonDependencyImpl#getParam2 <em>Param2</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ComparisonDependencyImpl extends GeneralAtomicImpl implements ComparisonDependency
{
  /**
   * The cached value of the '{@link #getParam1() <em>Param1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParam1()
   * @generated
   * @ordered
   */
  protected Param param1;

  /**
   * The default value of the '{@link #getArithOp() <em>Arith Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArithOp()
   * @generated
   * @ordered
   */
  protected static final String ARITH_OP_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getArithOp() <em>Arith Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getArithOp()
   * @generated
   * @ordered
   */
  protected String arithOp = ARITH_OP_EDEFAULT;

  /**
   * The cached value of the '{@link #getParam2() <em>Param2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getParam2()
   * @generated
   * @ordered
   */
  protected Param param2;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ComparisonDependencyImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return InterparameterDependenciesLanguagePackage.Literals.COMPARISON_DEPENDENCY;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Param getParam1()
  {
    return param1;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParam1(Param newParam1, NotificationChain msgs)
  {
    Param oldParam1 = param1;
    param1 = newParam1;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1, oldParam1, newParam1);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParam1(Param newParam1)
  {
    if (newParam1 != param1)
    {
      NotificationChain msgs = null;
      if (param1 != null)
        msgs = ((InternalEObject)param1).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1, null, msgs);
      if (newParam1 != null)
        msgs = ((InternalEObject)newParam1).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1, null, msgs);
      msgs = basicSetParam1(newParam1, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1, newParam1, newParam1));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getArithOp()
  {
    return arithOp;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setArithOp(String newArithOp)
  {
    String oldArithOp = arithOp;
    arithOp = newArithOp;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__ARITH_OP, oldArithOp, arithOp));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Param getParam2()
  {
    return param2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetParam2(Param newParam2, NotificationChain msgs)
  {
    Param oldParam2 = param2;
    param2 = newParam2;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2, oldParam2, newParam2);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setParam2(Param newParam2)
  {
    if (newParam2 != param2)
    {
      NotificationChain msgs = null;
      if (param2 != null)
        msgs = ((InternalEObject)param2).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2, null, msgs);
      if (newParam2 != null)
        msgs = ((InternalEObject)newParam2).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2, null, msgs);
      msgs = basicSetParam2(newParam2, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2, newParam2, newParam2));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1:
        return basicSetParam1(null, msgs);
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2:
        return basicSetParam2(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1:
        return getParam1();
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__ARITH_OP:
        return getArithOp();
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2:
        return getParam2();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1:
        setParam1((Param)newValue);
        return;
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__ARITH_OP:
        setArithOp((String)newValue);
        return;
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2:
        setParam2((Param)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1:
        setParam1((Param)null);
        return;
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__ARITH_OP:
        setArithOp(ARITH_OP_EDEFAULT);
        return;
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2:
        setParam2((Param)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM1:
        return param1 != null;
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__ARITH_OP:
        return ARITH_OP_EDEFAULT == null ? arithOp != null : !ARITH_OP_EDEFAULT.equals(arithOp);
      case InterparameterDependenciesLanguagePackage.COMPARISON_DEPENDENCY__PARAM2:
        return param2 != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (arithOp: ");
    result.append(arithOp);
    result.append(')');
    return result.toString();
  }

} //ComparisonDependencyImpl
