IF p1 THEN NOT p2=='A';

IF p1=='A' THEN p2 OR p3 OR p4;

p1 >= p2;

AllOrNone(p1, p2);

Or(p1, p2);

OnlyOne(p1, p2);

IF p1 THEN p2 AND p3;

OnlyOne(p1, p2, p3);

OnlyOne(p1, p2, p3, p4, p5, p6);

IF p1=='A' THEN p2;

IF p1=='A' THEN p2=='B';

OnlyOne(p1, p2, p3, p4);

ZeroOrOne(p1, p2, p3, p4);

IF p1 THEN p2=='A';

ZeroOrOne(p1, p2);

OnlyOne(p1, p2, p3, p4, p5);

IF p1 THEN p2;

IF NOT p1 THEN p2 OR p3;

AllOrNone(p1, p2=='A');

IF p1 THEN p2 AND p3=='A';

IF p1=='A' THEN OnlyOne(p2 AND p3, p4 AND p5);

IF p1 THEN OnlyOne(p2=='A', p3=='B' AND (p4 OR p5));

OnlyOne(p1, p2, p3 AND p4);

OnlyOne(p1, p2 AND p3);

OnlyOne(p1 AND p2, p3 AND p4);

OnlyOne(p1, p2, p3 OR p4);

IF p1 THEN NOT (p2 OR p3);

IF NOT p1 THEN p2 OR (p3 AND p4);

OnlyOne(p1, p2, p3, p4, p5, p6, p7, p8, p9, p10);

ZeroOrOne(p1, p2, p3);

IF p1=='A' THEN OnlyOne(p2, p3, p4);

IF p1=='A' THEN OnlyOne(p2, p3);

IF p1=='A' THEN p2 OR p3;

p1==p2;

AllOrNone(p1=='A', p2=='B');

IF p1 THEN p2=='A' OR p3;

IF p1 THEN p2=='A' AND p3>100 AND p4=='C';

Or(p1, p2, p3);

AllOrNone(p1, p2, p3);

p1 + p2 + p3 + p4 == 100;

IF NOT p1 THEN p2=='A';

IF p1 THEN OnlyOne(p2, p3);

IF p1 THEN Or(p2, p3, p4, p5, p6);

IF NOT p1 THEN NOT (p2 OR p3);

IF NOT p1 THEN NOT (p2 OR p3 OR p4);

AllOrNone(p1, Or(p2, p3));

IF NOT p1=='A' THEN ZeroOrOne(p2, p3);

IF p1 THEN NOT (p2 OR p3 OR p4);


