[p1]<=[p2];

[p1]+[p2]*[p3]-[p4]==100;

IF NOT [p1] AND ([p3] OR [p4]!=100) THEN [p2]==false;

IF [p1]=='A' THEN [p2]>=10.01;

Or([p1], [p2], [p3]);

ZeroOrOne([p1], [p2], [p3]);

AllOrNone([p1], [p2], [p3]);

OnlyOne([p1], [p2], [p3]); //

IF [p1] AND NOT [p2]=='A'|'B' OR ([p3]>[p4] AND [p5]*([p6]+[p7])<200) THEN AllOrNone([p8], [p9]>=[p10], ZeroOrOne([p11], [p12]), [p13]+[p14]==10) AND ([p15] OR NOT [p16]) OR [p17];

