Or([p1], [p2]);
Or([p1], [p2], [p3]); //
NOT ZeroOrOne([p1], [p2]<[p3], [p3]=='A'|'B', [p4] OR ([p5] AND [p6]));
IF [p1] OR ([p2] AND [p3]) THEN [p1]<[p2] AND ZeroOrOne([p4], [p5], [p6]) OR [p2]>=[p3] OR AllOrNone(AllOrNone([p5], [p6], [p7]<=[p8]), [p3], ZeroOrOne([p1], [p2], AllOrNone([p3], [p4]))) AND [p]!=[q] OR [p2]<=[p3] OR [p9] AND NOT [pp]; //
IF [p1]<[p2] THEN [p3]<[p4];
ZeroOrOne([p1]>[p2], [p14]=='A', [p3] AND [p4] OR ([p5] AND [p6] OR [p7] AND ([p9] AND [p10]) OR [pli]) AND [p8] AND ([p12] AND [p13])); //
IF NOT ([p1] AND NOT ([p2] OR ([p3] AND [p4]))) OR NOT ZeroOrOne([p1], [p2]) THEN [p3];
IF AllOrNone([p1], [p2], [p3] AND [p2]>[p3]) THEN NOT ([p4] AND [p5]) OR [p6]<[p7]; //
IF [p7] AND [p1]+[p2]==100 THEN [p4] AND NOT [p5];
IF [p1]+[p2]==100 AND [p4] OR ([p2]+[p3]==100 AND [p3]) THEN [p4] AND NOT [p5];

IF [p1]=='A'|'B'|'Cosasasa' AND Or([p1], [p2], [p3]=='A'|'C') THEN (NOT ([p1]-[p2]>200) AND [p7]=='Boca'|'Cabo') OR [p3];


IF [p1] AND NOT ([p1] AND [p2]) OR [p3] THEN [p3] OR NOT [p4] AND [p5];

AllOrNone([p1], [p2], [p3]);

OnlyOne([p1], [p2]);

IF [p1] AND [p2]<[p3] AND NOT [p2]=='A'|'B' OR ([p3]>[p4] AND [p5]*([p6]+[p7])<200) THEN AllOrNone([p8], [p9]>=[p10], ZeroOrOne([p11], [p12]), [p13]+[p14]==10) AND ([p15] OR NOT [p16]) OR [p17];

[p1]+[p2]*[p3]-[p4]==100;

IF [p1]=='Hola?hey*adios' THEN [p2];
IF p1 LIKE 'Hola?hey*adios' THEN [p2];

Or([p1-:/p3], p2);
